### ISSUE TITLE
Update engines to latest version

### ISSUE THREAD

**Issue by ghost** [nguyenpham/banksiagui-ios#1]
According to this talkchess.com post here, the version of Ethereal used in Banksia-iOS is Ethereal 12.50 and the version of Igel used is Igel 2.6:

http://talkchess.com/forum3/viewtopic.php?f=2&t=75592&start=10#p874037

However, Ethereal 12.75 was released on 9 October 2020 and Igel 2.8 was released on 23 September 2020.

**Comment by nguyenpham** [comment]
Updated 3 engines:
- SF: 16
- Lc0: 0.30
- RubiChess: 2.2
Other engines have been removed because:
- one changed (partly) to commercial
- all others did not update for a while
- reduce the size of the app

https://github.com/nguyenpham/banksiagui-ios/commit/ad5eb84827a5d4645078eb823a8b4bbfacbc3428
