### ISSUE TITLE
missing .xcodeproj

### ISSUE THREAD

**Issue by victorcampeanu** [nguyenpham/banksiagui-ios#2]
thank you for the effort to put this together! however it is missing the main file. .xcodeproj. I see it is added to gitignore

I tried to configure mine from scratch but it has a lot of errors.

**Comment by nguyenpham** [comment]
Thank you. Fixed by https://github.com/nguyenpham/banksiagui-ios/commit/2f50f45818d35bfc1f91642f30761414dc0ba19d
